config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :pizzas
  end
  root 'restaurants#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pizza.rb
class Pizza < ApplicationRecord
  belongs_to :restaurant
  PIZZA_TYPE = %w(Margherita Funghi Capricciosa Marinara Peperoni Napolitana Hawaii Rucola Bolognese)

  validates :name, :price, :ingredients, :restaurant_id, presence: true
  validates_numericality_of :price, greater_than_or_equal_to: 0, less_than: 100000
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  DAYS = %w(Monday Tuesday Wednesday Thursday Friday Saturday Sunday)

  enum opening_day: DAYS, _prefix: :opens_at
  enum closing_day: DAYS, _prefix: :closes_at

  has_many :pizzas

  validates :name, uniqueness: true, presence:true
  validates :address, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :get_restaurant
  before_action :set_pizza, only: [:show, :edit, :update, :destroy]

  def get_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def index
    @pizzas = @restaurant.pizzas
  end

  def show
  end

  def new
    @pizza = Pizza.new
  end

  def edit
  end

  def create
    @pizza = @restaurant.pizzas.new(pizza_params)

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to [@restaurant, @pizza], notice: 'Pizza was successfully created.' }
        format.json { render :show, status: :created, location: [@restaurant, @pizza] }
      else
        format.html { render :new }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @pizza.update(pizza_params)
        format.html { redirect_to [@restaurant, @pizza], notice: 'Pizza was successfully updated.' }
        format.json { render :show, status: :ok, location: [@restaurant, @pizza] }
      else
        format.html { render :edit }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pizza.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_pizzas_url, notice: 'Pizza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_pizza
      @pizza = @restaurant.pizzas.find(params[:id])
    end

    def pizza_params
      params.require(:pizza).permit(:name, :price, :ingredients, :restaurant_id)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :opening_time, :closing_time, :opening_day, :closing_day)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
  def price(amount)
    number_to_currency(amount, unit: "PLN", separator: ",", delimiter: "", format: "%n %u")
  end 
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def shortest_timme(full_time)
    full_time.strftime("%R") if full_time
  end

  def week_days
    Restaurant::DAYS
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PizzaPlace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container-fluid
      .col-md-10.col-md-offset-1
        = yield

app/views/pizzas/_form.html.haml
= simple_form_for [@restaurant, @pizza] do |f|
  .group-field
    = f.input :name
    = f.input :price, as: :float
    = f.input :ingredients
  .group-actions
    = link_to 'Back', restaurant_pizzas_path(@restaurant), class: 'btn btn-default'
    = f.button :submit

app/views/pizzas/_pizza.html.haml
%tr
  %td= pizza.name
  %td= price(pizza.price)
  %td= pizza.ingredients
  %td
    = link_to [@restaurant, pizza], { title: "Show" } do
      %button.btn.btn-default
        = fa_icon "search"
    = link_to edit_restaurant_pizza_path(@restaurant, pizza), { title: "Edit" } do
      %button.btn.btn-default
        = fa_icon "edit"
    = link_to [@restaurant, pizza], { :method => :delete, title: "Delete" } do
      %button.btn.btn-default
        = fa_icon "times"

app/views/pizzas/edit.html.haml
%h1 Editing pizza

= render 'form'

app/views/pizzas/index.html.haml
%h1 Menu
%h2
  This restaurant have
  = pluralize(@restaurant.pizzas.count, "pizza")

%table.table.table-condensed
  %thead
    %tr
      %th Name
      %th Price
      %th Ingredients
      %th Action

  %tbody
    = render @pizzas
%br

= link_to 'New Pizza', new_restaurant_pizza_path(@restaurant), class: 'btn btn-info'
= link_to 'Restaurant list', restaurants_path, {class: 'btn btn-default', title: "Back"}

app/views/pizzas/new.html.haml
%h1 New pizza

= render 'form'

app/views/pizzas/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @pizza.name
%p
  %b Price:
  = price(@pizza.price)
%p
  %b Ingredients:
  = @pizza.ingredients
%p
  %b Restaurant:
  = @pizza.restaurant.name

= link_to 'Edit', edit_restaurant_pizza_path(@restaurant), class: 'btn btn-default'
\|
= link_to 'Back', restaurant_pizzas_path(@restaurant), class: 'btn btn-default'

app/views/restaurants/_form.html.haml
= simple_form_for restaurant do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :address
    = f.input :opening_time
    = f.input :closing_time
    = f.input :opening_day, collection: week_days, label_method: :capitalize, include_blank: true
    = f.input :closing_day, collection: week_days.reverse, blank: true
  .form-actions
    = link_to 'Back', restaurants_path, class: 'btn btn-default'
    = f.button :submit

app/views/restaurants/_restaurant.html.haml
%tr
  %td= restaurant.name
  %td= restaurant.address
  %td= link_to pluralize(restaurant.pizzas.count, "Dish"),restaurant_pizzas_path(restaurant), class: 'btn btn-default'
  %td= shortest_timme(restaurant.opening_time)
  %td= shortest_timme(restaurant.closing_time)
  %td= restaurant.opening_day
  %td= restaurant.closing_day
  %td
    = link_to restaurant, { title: "Show" } do
      %button.btn.btn-default
        = fa_icon "search"
    = link_to edit_restaurant_path(restaurant), { title: "Edit" } do
      %button.btn.btn-default
        = fa_icon "edit"
    = link_to restaurant, { method: :delete, title: "Destroy" } do
      %button.btn.btn-default
        = fa_icon "times"

app/views/restaurants/edit.html.haml
%h1 Editing Restaurant
= render 'form', restaurant: @restaurant

app/views/restaurants/index.html.haml
%p#notice= notice
%h1= pluralize(@restaurants.count, "Restaurants")

%table.table.table-condensed
  %thead
    %tr
      %th Name
      %th Address
      %th Menu
      %th Openings time
      %th Closings time
      %th Opening day
      %th Closing day
      %th Actions
  %tbody
    = render @restaurants
%br/
= link_to 'New Restaurant', new_restaurant_path, class: 'btn btn-info'

app/views/restaurants/new.html.haml
%h1 New Restaurant
= render 'form', restaurant: @restaurant

app/views/restaurants/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @restaurant.name
%p
  %strong Address:
  = @restaurant.address
%p
  %strong Openings time:
  = shortest_timme(@restaurant.opening_time)
%p
  %strong Closings time:
  = shortest_timme(@restaurant.closing_time)
%p
  %strong Opening day:
  = @restaurant.opening_day

  %strong Closing day:
  = @restaurant.closing_day
= link_to 'Edit', edit_restaurant_path(@restaurant), class: 'btn btn-default'
|
= link_to 'Back', restaurants_path, class: 'btn btn-default'